const SHOW_MOVIES_LINKED = "SHOW_MOVIES_LINKED";
const FIND_MOVIES = "FIND_MOVIES";
const SHOW_MOVIE_CINEMAS = "SHOW_MOVIE_CINEMAS";
const SHOW_ALL_CINEMAS = "SHOW_ALL_CINEMAS";
const SHOW_ALL_MOVIES = "SHOW_ALL_MOVIES";
const GET_HOUSE = "GET_HOUSE";
const SWITCH_VISIBLE = "SWITCH_VISIBLE";
const SWITCH_VISIBLE_ADD = "SWITCH_VISIBLE_ADD";
const SWITCH_VISIBLE_SESSION = "SWITCH_VISIBLE_SESSION";
const GET_LINKED_CINEMA = "GET_LINKED_CINEMA";
export {
    SHOW_MOVIES_LINKED,FIND_MOVIES,SHOW_MOVIE_CINEMAS,SHOW_ALL_CINEMAS,SHOW_ALL_MOVIES,SWITCH_VISIBLE,SWITCH_VISIBLE_ADD,GET_HOUSE,GET_LINKED_CINEMA,SWITCH_VISIBLE_SESSION
}
