const SHOW_MOVIES_LINKED = "SHOW_MOVIES_LINKED";
const FIND_MOVIES = "FIND_MOVIES";
const SHOW_MOVIE_CINEMAS = "SHOW_MOVIE_CINEMAS";
const SHOW_ALL_CINEMAS = "SHOW_ALL_CINEMAS";
const SHOW_ALL_MOVIES = "SHOW_ALL_MOVIES";
const SWITCH_VISIBLE = "SWITCH_VISIBLE";
const SWITCH_VISIBLE_ADD = "SWITCH_VISIBLE_ADD";
export {
    SHOW_MOVIES_LINKED,FIND_MOVIES,SHOW_MOVIE_CINEMAS,SHOW_ALL_CINEMAS,SHOW_ALL_MOVIES,SWITCH_VISIBLE,SWITCH_VISIBLE_ADD
}