const SHOW_DATA = "SHOW_DATA"
const SHOW_USERS = "SHOW_USERS"
const FIND_USERS = "FIND_USERS"
const SET_UPDATEVISIBLE = "SET_UPDATEVISIBLE"
const DELETE_USERS = "DELETE_USERS"
const RENDERER_USERS = "RENDERER_USERS"
const PAGE_SIZE = "PAGE_SIZE"

export {SHOW_DATA,SHOW_USERS,FIND_USERS,SET_UPDATEVISIBLE,DELETE_USERS,PAGE_SIZE};