const NEWS_DATA = "NEWS_DATA"
const SEARCH_DATA = "SEARCH_DATA"
const DEL_DATA = "DEL_DATA"
const EDIT_DATA = "EDIT_DATA"
const EDIT_VISBLE = "EDIT_VISBLE"

export {NEWS_DATA,SEARCH_DATA,DEL_DATA,EDIT_DATA,EDIT_VISBLE}